const express = require("express");
const cors = require('cors');
require('dotenv').config();
const app = express();
const PORT = process.env.PORT;
const db = require("./models");
const bodyParser = require("body-parser");
const cookieParser = require("cookie-parser");

const authRouter = require('./router/auth-router/auth-router');
const contactRouter = require("./router/contact-router/contact-router");
const productRouter = require("./router/product-router/product-router");
const orderRouter = require("./router/order-router/order-router");

const paymentRouter = require("./router/payment-router/payment-router");
const globalErrorHandler = require("./controllers/globalErrorHandler/globalErrorHandler");
const catchAsync = require("./utils/catchAsync");
const AppError = require("./utils/appError");

app.use(express.json()); //middleware
app.use(cookieParser());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.use(cors({
  origin: 'http://localhost:5173',
  methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
  credentials: true,
  optionsSuccessStatus: 204,
}));

//rest api end point
app.use("/api/auth", authRouter);
app.use("/api/product", productRouter);
app.use("/api/order", orderRouter);
app.use("/api/payment", paymentRouter);


app.use('*',
  catchAsync(async (req, res, next) => {
      // provide custom error message generated by user
      throw new AppError(`Can't find ${req.originalUrl} on this server`, 404)

      // provide error message through global error handler by using catchAsync middleware way without using try catch block
      // throw new Error(`Can't find ${req.originalUrl} on this server`);

      // provide default error message  through global error handler for async function
      // return next(new Error(`Can't find ${req.originalUrl} on this server`))

      // provide error message through global error handler for normal function
      // throw new Error(`Can't find ${req.originalUrl} on this server`);

      // default way to provide error message 
      // res.status(404).json({
      //     status: 'fail',
      //     message: `Can't find ${req.originalUrl} on this server`
      // })
  }))

//global error handler
app.use(globalErrorHandler);

db.sequelize
  .sync({ force: false })
  .then(() => {
    app.listen(PORT, () => {
      console.log(`Server is running on port ${PORT}`);
      console.log("Database connected successfully");
    })
  })
  .catch((err) => {
    console.error("Error syncing database:", err);
  });